language: objective-c
osx_image: xcode7.3
xcode_workspace: demo/demo.xcworkspace 
xcode_scheme: demo
xcode_sdk: iphonesimulator
env: CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
notifications:
  email: false
